// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsezvrmjnsjcfhczudth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzZXp2cm1qbnNqY2ZoY3p1ZHRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODMxMTMsImV4cCI6MjA2NjM1OTExM30.BpLnJ6xWVWwraFBZoj5lvcCnpzcsCy1E3pVLEgAIaRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);